### ISSUE TITLE
[Error: undefined Unable to resolve module ./src/Reels/components/Reels from /home/abhi/intrn/refractor/grabbit-live-frontend/node_modules/react-native-instagram-reels/index.js:

### ISSUE THREAD

**Issue by dev-abhi89** [kartikeyvaish/react-native-instagram-reels#1]
`[Error: undefined Unable to resolve module ./src/Reels/components/Reels from /home/abhi/intrn/refractor/grabbit-live-frontend/node_modules/react-native-instagram-reels/index.js: 

None of these files exist:
  * node_modules/react-native-instagram-reels/src/Reels/components/Reels(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules/react-native-instagram-reels/src/Reels/components/Reels/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
> 1 | import Reels from "./src/Reels/components/Reels";`

**Comment by kartikeyvaish** [comment]
Yes, I will update it soon.
